//===----------------------------------------------------------------------===//
// Copyright © 2024-2026 Apple Inc. and the Pkl project authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//

package pkl

import "reflect"

var schemas = make(map[string]reflect.Type)

// RegisterMappingFor associates the type given the Pkl name to the corresponding Go type.
//
//goland:noinspection GoUnnecessarilyExportedIdentifiers
func RegisterMappingFor[T any](name string) {
	schemas[name] = reflect.TypeFor[T]()
}

// RegisterStrictMapping associates the type given the Pkl name to the corresponding Go type.
//
// Deprecated: Replaced by [RegisterMappingFor]. Retained for compatibility with code generated by
// pkl-go releases prior to v0.14.0.
//
//goland:noinspection GoUnnecessarilyExportedIdentifiers
func RegisterStrictMapping(name string, value any) {
	schemas[name] = reflect.TypeOf(value)
}

// RegisterMapping is like RegisterStrictMapping, but casts it to a pointer.
//
// Deprecated: Replaced by [RegisterMappingFor]. Retained for compatibility with code generated by
// pkl-go releases prior to v0.14.0 where object types were generated as pointers.
//
//goland:noinspection GoDeprecation,GoUnnecessarilyExportedIdentifiers
func RegisterMapping(name string, value any) {
	schemas[name] = reflect.PointerTo(reflect.TypeOf(value))
}
